name: Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: 'Quality Checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run Prettier check
        run: npm run prettier-check

      - name: Run ESLint check
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Run tests
        run: npm run test
